In [22]:
import pandas as pd 
%matplotlib inline
import matplotlib.pyplot as plt
dates = pd.read_csv("filtered_announced_data.csv");
data = pd.read_csv("filtered_data.csv");

In [23]:
dates['Announced'] = pd.to_datetime(dates['Announced'])
dates['Closed'] = pd.to_datetime(dates['Closed'])
data['Date'] = pd.to_datetime(data['Date'])

In [48]:
# dates.head()
data.head()

,Unnamed: 0,Date,ASTS,ASTSW,NPAUU,INVZ,INVZW,CGROU,FOA,FOA/WS,...,HYACU,ASLE,ASLEW,MNCLU,XL,GOEV,GOEVW,CLVR,CLVRW,SAMAU
0,1,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2019-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2019-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2019-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
tickers = list(data.columns.values);
tickers = tickers[2:];
for ticker in tickers:
    if(list(dates[dates["Ticker"] == ticker].index) != []):
        announceDate = dates["Announced"][dates[dates["Ticker"] == ticker].index[0]]
        closeDate = dates["Closed"][dates[dates["Ticker"] == ticker].index[0]]
        announceIndex = data[data['Date'] == announceDate].index[0] + 1 # +1 since filing can happene wwhenver
        closeIndex = data[data['Date'] == closeDate].index[0] + 1 

        start = data[ticker][announceIndex];
        end = data[ticker][announceIndex + 2];
        print (ticker, end - start)
tickers[::3]

ASTS -0.5
INVZ -1.1500000000000004
FOA 0.0
PSFE 0.8000000000000007
ARVL 3.6400000000000006
NVVE 0.015000000000000568
LBPS nan
PCT -0.10999999999999943
AEVA 0.0600000000000005
OUST 2.17
VIEW 0.2550000000000008
CHPT 3.0699999999999985
BFLY 3.75
NUVB -0.3550000000000004
MILE 2.3000000000000007
ETWO 0.254999999999999
ADN 0.009999999999999787
UWMC -0.09999999999999964
HIMS -0.47000000000000064
BTRS -0.6000000000000014
CLOV nan
BMTX nan
RMO nan
RSI nan
PRCH nan
VINC nan
ARKO nan
ASLE nan
XL nan
GOEV nan
CLVR nan

['ASTS',
 'INVZ',
 'FOA',
 'PSFE',
 'ARVL',
 'NVVE',
 'NBACU',
 'LOACR',
 'PCTTW',
 'AEVA/WS',
 'OUST/WS',
 'VIEWW',
 'CHPT/WS',
 'BFLY/WS',
 'NUVB/WS',
 'MILEW',
 'ETWO/WS',
 'ADNWW',
 'UWMC/WS',
 'HIMS/WS',
 'BTRSW',
 'CLOVW',
 'BMTX/WS',
 'RMO/WS',
 'RB009KR8 M-Mkt',
 'RB009KRR M-Mkt',
 'VINCU',
 'HYACU',
 'MNCLU',
 'GOEVW',
 'SAMAU']