In [8]:
import pandas as pd 
import numpy as np
df = pd.read_excel("spacData.xlsx", engine='openpyxl')
df.head()

,Unnamed: 0,ASTS US Equity,Unnamed: 2,Unnamed: 3,ASTSW US Equity,Unnamed: 5,Unnamed: 6,NPAUU US Equity,Unnamed: 8,Unnamed: 9,...,Unnamed: 264,CLVR US Equity,Unnamed: 266,Unnamed: 267,CLVRW US Equity,Unnamed: 269,Unnamed: 270,SAMAU US Equity,Unnamed: 272,Unnamed: 273
0,Dates,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,...,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID
1,2019-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
column_names = list(df.columns)
column_names[0] = 'Date'
df.columns = column_names
df.columns.str.match("Unnamed")
df = df.loc[:,~df.columns.str.match("Unnamed")]
tickers = [x.split(' US Equity')[0] for x in list(df.columns)]
df.columns = tickers
df = df.drop(0)
df.head()

TypeError: 'numpy.int32' object is not callable

In [14]:
df = df[:596]

In [17]:
df.to_csv('filtered_data.csv')

In [42]:
tickers = [x.split(' US Equity')[0] for x in list(df.columns) if "Unnamed" not in x]
# for i in range(len(tickers)):
#     for j in range(3):
#         tickers.insert(i+1, tickers[i])
#         print(i+1, tickers[i+1])

In [49]:
triple_tickers = [[x,x,x] for x in tickers]
triple_tickers = np.reshape(triple_tickers, 3*len(triple_tickers))
triple_tickers = list(triple_tickers)
triple_tickers.insert(0,'Date')

In [50]:
triple_tickers

['Date',
 'ASTS',
 'ASTS',
 'ASTS',
 'ASTSW',
 'ASTSW',
 'ASTSW',
 'NPAUU',
 'NPAUU',
 'NPAUU',
 'INVZ',
 'INVZ',
 'INVZ',
 'INVZW',
 'INVZW',
 'INVZW',
 'CGROU',
 'CGROU',
 'CGROU',
 'FOA',
 'FOA',
 'FOA',
 'FOA/WS',
 'FOA/WS',
 'FOA/WS',
 'RPLA/U',
 'RPLA/U',
 'RPLA/U',
 'PSFE',
 'PSFE',
 'PSFE',
 'PSFE/WS',
 'PSFE/WS',
 'PSFE/WS',
 'BFT/U',
 'BFT/U',
 'BFT/U',
 'ARVL',
 'ARVL',
 'ARVL',
 'ARVLW',
 'ARVLW',
 'ARVLW',
 'CIICU',
 'CIICU',
 'CIICU',
 'NVVE',
 'NVVE',
 'NVVE',
 'NVVEW',
 'NVVEW',
 'NVVEW',
 'NBACR',
 'NBACR',
 'NBACR',
 'NBACU',
 'NBACU',
 'NBACU',
 'LBPS',
 'LBPS',
 'LBPS',
 'LBPSW',
 'LBPSW',
 'LBPSW',
 'LOACR',
 'LOACR',
 'LOACR',
 'LOACW',
 'LOACW',
 'LOACW',
 'PCT',
 'PCT',
 'PCT',
 'PCTTW',
 'PCTTW',
 'PCTTW',
 'ROCHU',
 'ROCHU',
 'ROCHU',
 'AEVA',
 'AEVA',
 'AEVA',
 'AEVA/WS',
 'AEVA/WS',
 'AEVA/WS',
 'IPV/U',
 'IPV/U',
 'IPV/U',
 'OUST',
 'OUST',
 'OUST',
 'OUST/WS',
 'OUST/WS',
 'OUST/WS',
 'RB009KRY M-Mkt',
 'RB009KRY M-Mkt',
 'RB009KRY M-Mkt',
 'VIEW',
 'VIEW',
 'VIEW',
 'VIEWW',
 'VIEWW',
 'VIEWW',
 'RB009KR2 M-Mkt',
 'RB009KR2 M-Mkt',
 'RB009KR2 M-Mkt',
 'CHPT',
 'CHPT',
 'CHPT',
 'CHPT/WS',
 'CHPT/WS',
 'CHPT/WS',
 'RB00ATG6 M-Mkt',
 'RB00ATG6 M-Mkt',
 'RB00ATG6 M-Mkt',
 'BFLY',
 'BFLY',
 'BFLY',
 'BFLY/WS',
 'BFLY/WS',
 'BFLY/WS',
 'RB00ASG3 M-Mkt',
 'RB00ASG3 M-Mkt',
 'RB00ASG3 M-Mkt',
 'NUVB',
 'NUVB',
 'NUVB',
 'NUVB/WS',
 'NUVB/WS',
 'NUVB/WS',
 'RB00A7K1 M-Mkt',
 'RB00A7K1 M-Mkt',
 'RB00A7K1 M-Mkt',
 'MILE',
 'MILE',
 'MILE',
 'MILEW',
 'MILEW',
 'MILEW',
 'RB00AZ9Z M-Mkt',
 'RB00AZ9Z M-Mkt',
 'RB00AZ9Z M-Mkt',
 'ETWO',
 'ETWO',
 'ETWO',
 'ETWO/WS',
 'ETWO/WS',
 'ETWO/WS',
 'RB009KRW M-Mkt',
 'RB009KRW M-Mkt',
 'RB009KRW M-Mkt',
 'ADN',
 'ADN',
 'ADN',
 'ADNWW',
 'ADNWW',
 'ADNWW',
 'AMCIU',
 'AMCIU',
 'AMCIU',
 'UWMC',
 'UWMC',
 'UWMC',
 'UWMC/WS',
 'UWMC/WS',
 'UWMC/WS',
 'RB009LBJ M-Mkt',
 'RB009LBJ M-Mkt',
 'RB009LBJ M-Mkt',
 'HIMS',
 'HIMS',
 'HIMS',
 'HIMS/WS',
 'HIMS/WS',
 'HIMS/WS',
 'RB009ZQC M-Mkt',
 'RB009ZQC M-Mkt',
 'RB009ZQC M-Mkt',
 'BTRS',
 'BTRS',
 'BTRS',
 'BTRSW',
 'BTRSW',
 'BTRSW',
 'SMMC/U',
 'SMMC/U',
 'SMMC/U',
 'CLOV',
 'CLOV',
 'CLOV',
 'CLOVW',
 'CLOVW',
 'CLOVW',
 'RB009KS5 M-Mkt',
 'RB009KS5 M-Mkt',
 'RB009KS5 M-Mkt',
 'BMTX',
 'BMTX',
 'BMTX',
 'BMTX/WS',
 'BMTX/WS',
 'BMTX/WS',
 'RB00B9ZA M-Mkt',
 'RB00B9ZA M-Mkt',
 'RB00B9ZA M-Mkt',
 'RMO',
 'RMO',
 'RMO',
 'RMO/WS',
 'RMO/WS',
 'RMO/WS',
 'RSI',
 'RSI',
 'RSI',
 'RSI/WS',
 'RSI/WS',
 'RSI/WS',
 'RB009KR8 M-Mkt',
 'RB009KR8 M-Mkt',
 'RB009KR8 M-Mkt',
 'PRCH',
 'PRCH',
 'PRCH',
 'PRCHW',
 'PRCHW',
 'PRCHW',
 'RB009KRR M-Mkt',
 'RB009KRR M-Mkt',
 'RB009KRR M-Mkt',
 'VINC',
 'VINC',
 'VINC',
 'VINCW',
 'VINCW',
 'VINCW',
 'VINCU',
 'VINCU',
 'VINCU',
 'ARKO',
 'ARKO',
 'ARKO',
 'ARKOW',
 'ARKOW',
 'ARKOW',
 'HYACU',
 'HYACU',
 'HYACU',
 'ASLE',
 'ASLE',
 'ASLE',
 'ASLEW',
 'ASLEW',
 'ASLEW',
 'MNCLU',
 'MNCLU',
 'MNCLU',
 'XL',
 'XL',
 'XL',
 'GOEV',
 'GOEV',
 'GOEV',
 'GOEVW',
 'GOEVW',
 'GOEVW',
 'CLVR',
 'CLVR',
 'CLVR',
 'CLVRW',
 'CLVRW',
 'CLVRW',
 'SAMAU',
 'SAMAU',
 'SAMAU']

In [51]:
df.columns = triple_tickers

In [58]:
df

,Date,ASTS,ASTS,ASTS,ASTSW,ASTSW,ASTSW,NPAUU,NPAUU,NPAUU,...,GOEVW,CLVR,CLVR,CLVR,CLVRW,CLVRW,CLVRW,SAMAU,SAMAU,SAMAU
0,Dates,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,...,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID,PX_CLOSE_1D,PX_ASK,PX_BID
1,2019-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-01-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-01-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.94,10.35,10,9.92,2.45,2.38,2.3,NaN,NaN,NaN
2939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.14,9.99,10.34,10.26,2.39,2.39,2.38,NaN,NaN,NaN
2940,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.01,10.27,12.15,12.1,2.38,3.26,3.24,NaN,NaN,NaN
2941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.68,12.15,10.97,10.95,3.2601,2.76,2.75,NaN,NaN,NaN
2942,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.65,10.97,11.89,11.82,2.75,3.05,3.02,NaN,NaN,NaN

In [8]:
announced_df = pd.read_csv("spac-research.csv", encoding = "ISO-8859-1")

In [9]:
announced_df.head()

,SPAC,Newco,Ticker,Announced,Closed,TEV ($M),TEV/IPO,Sector,Geography,Redeemed,...,Director 13,Director 14,Director 15,Date +3mo,Date +6mo,Date +12mo,Date +0mo Price,Date +3mo Price,Date +6mo Price,Date +12mo Price
0,New Providence Acq,AST SpaceMobile,ASTS,12/16/2020,4/6/2021,"1,392",605%,Technology,US/Canada,NaN,...,NaN,NaN,NaN,7/5/2021,10/3/2021,4/1/2022,NaN,8.660,NaN,NaN
1,Collective Growth,Innoviz Technologies,INVZ,12/11/2020,4/5/2021,"1,033",689%,Automotive,Europe,NaN,...,NaN,NaN,NaN,7/4/2021,10/2/2021,3/31/2022,NaN,10.845,NaN,NaN
2,Replay Acq,Finance of America,FOA,10/13/2020,4/1/2021,"2,012",700%,Financial,US/Canada,68.70%,...,NaN,NaN,NaN,6/30/2021,9/28/2021,3/27/2022,NaN,10.085,NaN,NaN
3,Foley Trasimene II,Paysafe,PSFE,12/7/2020,3/30/2021,"9,000",613%,Financial,US/Canada,0.00%,...,NaN,NaN,NaN,6/28/2021,9/26/2021,3/25/2022,NaN,13.045,NaN,NaN
4,CIIG Merger,Arrival,ARVL,11/18/2020,3/24/2021,"5,400",2087%,Automotive,Europe,0.10%,...,NaN,NaN,NaN,6/22/2021,9/20/2021,3/19/2022,NaN,13.230,NaN,NaN