In [34]:
import pandas as pd

In [51]:
def uniq(test_list):
    res = []
    for i in test_list:
        if i not in res:
            res.append(i)
    return test_list

In [35]:
df= pd.read_csv('spac-research.csv')
df.head()

In [37]:
df[['President','CEO','Chairman']]

,President,CEO,Chairman
0,NaN,Abel Avellan,Abel Avellan
1,NaN,"Omer David Keilaf, MBA",Amichai Steimberg
2,#SPILL!,"Patricia L. Cook, MBA","Brian Lewis Libman, MBA"
3,NaN,"Philip McHugh, MBA","William Patrick Foley, II, MBA"
4,Avinash Rugoobur,Denis Sverdlov,"F. Peter Cuneo, MBA"
...,...,...,...
165,NaN,Long Deng,Long Deng
166,Tser Fah Chin,Tser Fah Chin,Tser Fah Chin
167,Andrew P. Callahan,Andrew P. Callahan,"Jerry D. Kaminski, MBA"
168,NaN,Sean R. Smith,"Steven J. Shapiro, MBA"
169,NaN,NaN,NaN

In [57]:
df['column_name'] = df['President']+ ' ' + df['CEO'] # + df['Director'] + ....

In [58]:
people = list(df['CEO'])
people.append(list(df['Chairman']))
# have another dozen statements appending a list of the names of directors and stuff
###############
people = uniq(people)
len(people), people
# removing the nan and removing the suffixes like MBA and PHD
people = [x.split(',')[0] for x in people if type(x) == str]
len(people), people

(155,
 ['Abel Avellan',
  'Omer David Keilaf',
  'Patricia L. Cook',
  'Philip McHugh',
  'Denis Sverdlov',
  'Gregory Poilasne',
  'Duncan Peyton',
  'Michael Otworth',
  'Soroush Salehian Dardashti',
  'Angus Pacala',
  'Rao P. Mulpuri',
  'Pasquale Romano',
  'Todd M. Fruchterman',
  'David T. Hung',
  'Ben Kohn',
  'Dan Preston',
  'Jason Meyenburg',
  'Michael Anthony Farlekas',
  'Vassilios Gregoriou',
  'Jonathan Webb',
  'Mat Ishbia',
  'Michael W. Bor',
  'Andrew Dudum',
  'Flint A. Lane',
  'Vivek Garipalli',
  'John Ho',
  'Luvleen Sidhu',
  'Robert Dee Etherington',
  'Stephen E. Croskrey',
  'Tilman Joseph Fertitta',
  'Lionel E. Selwood',
  'Gregory A. Carlin',
  'Matt Ehrlichman',
  'Ahmed Hamdy',
  'Arie E. Kotler',
  'Nicolas Finazzo',
  'Dimitri N. Kazarinoff',
  'Ulrich Kranz',
  'Kyle Detwiler',
  'Eric Wu',
  'Andrew C. Paradise',
  'Julio A. Ramirez',
  'Laxminarayan Bhat',
  'Ric Fulop',
  'Austin Russell',
  'Jagdeep Singh',
  'Antonino Ciappina',
  'James Henry Litinsky',
  'Zhuang Kun He',
  'Michael Jay Sacks',
  'Joe Mastrangelo',
  'Srinivas Koneru',
  'Jim N. Woody',
  'John W. Kalix',
  'Henrik Fisker',
  'Tanya Lynn Domier',
  'N. Anthony Coles',
  'Stephen S. Burns',
  'Jeff Ian Hack',
  'Salvatore Galletti',
  'Clint Stinchcomb',
  '#SPILL!',
  'Mark Howard Tabak',
  'Thomas J. Healy',
  'Richard Byworth',
  'Anand Gopalan',
  'Jacques Stern',
  'Dylan B. Lissette',
  'Jack D. Hightower',
  'Joseph L. Marinucci',
  'Harpreet Singh-Jasuja',
  'Michael Crawford',
  'Albert Manzone',
  'Chun Ning Wang',
  'John J. Flynn',
  'Mark A. Russell',
  'Diane Renee Garrett',
  'Xiao Wu He',
  'Jason D. Robins',
  'Xavier Williams',
  'Si Guang Peng',
  'Wasef Salim Abdulrahman Al-Jabsheh',
  'Andr�s Campos',
  'Leonard Livschitz',
  'Ryan Greenawalt',
  'L. Joe Boyer',
  'Bing Zhang',
  'Charles D. Peiffer',
  'Robert J. Johnson',
  'Todd R. Pedersen',
  'Christopher John Weiler',
  'Nicolaas Lammert Paardenkooper',
  'Roberta Lipson',
  'Peter Salzmann',
  'Dario Leopoldo Calogero',
  'Andrew H. Rubenstein',
  'Jeffrey B. Pyatt',
  '#SPILL!',
  'Jonathan Eithan Solomon',
  'Michael Colglazier',
  'Zu Guang Wang',
  'Michael Knott',
  'John D. Dobak',
  'Kwok Leung Ng',
  'Fred Ross',
  'John Morris',
  'Jeffery Peck',
  'Jessica Billingsley',
  'Omar Marwan Asali',
  'Yinglin Mark Xu',
  'Jerre Lee Stead',
  'Mingjun Lin',
  'Jia Sheng',
  'Leonard I. Fluxman',
  'James Brad Archer',
  'Federico Trucco',
  'T. J. Parass',
  'Thomas J. Leonard',
  'Alan S. Knitowski',
  'Kok Eng Lim',
  'Gary S. Gillheeney',
  'Bruce Franklin Young',
  'Roman Nehemiah Franklin',
  'Carl A. Grimstad',
  'David Clay Bretches',
  'Joel N. Broussard',
  'David Martin Roberts',
  'Daniel C. Herz',
  'Xiao Mou Zhang',
  'Stephen I. Chazen',
  'Robert Lisy',
  'Thomas C. Priore',
  'Sherif Foda',
  'John Paul Roehm',
  'William P. Murnane',
  'John A. McKenna',
  'Joseph B. Megibow',
  'Mark P. Castiglione',
  '#SPILL!',
  'Julio Cesar de S� Volot�o',
  'Chris Blunt',
  'Bradley L. Soultz',
  'Seth A. Ravin',
  'Sek Yuen Chan',
  'Matthew K. Schatzman',
  'Ronald C. Cogburn',
  'Joseph E. Scalzo',
  'Abel Clark',
  'John Bradley Fisher',
  'Bruce D. Wardinski',
  'Jonathan M. Shepko',
  'Long Deng',
  'Tser Fah Chin',
  'Andrew P. Callahan',
  'Sean R. Smith'])

In [59]:
df['column_name']
# use for loop to iterate through all executives in the people list
# use dataframe filtering to get only the rows that have the specific executive in df['column_name']

0                                        NaN
1                                        NaN
2              #SPILL! Patricia L. Cook, MBA
3                                        NaN
4            Avinash Rugoobur Denis Sverdlov
                       ...
165                                      NaN
166              Tser Fah Chin Tser Fah Chin
167    Andrew P. Callahan Andrew P. Callahan
168                                      NaN
169                                      NaN
Name: column_name, Length: 170, dtype: object